name: Update Publications Data

on:
  schedule:
    # Run every night at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-publications:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run publication update script
      run: node scripts/update-publications.js
      
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code public/data/hvp-publications.json || echo "changes=true" >> $GITHUB_OUTPUT
        
    - name: Commit and push if changed
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/data/hvp-publications.json
        git commit -m "Update publications data [skip ci]"
        git push